name: Build mpv-android (official arm64 release)

on:
  workflow_dispatch: # run manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git python3 unzip yasm nasm cmake meson ninja-build gettext \
            pkg-config autoconf automake libtool texinfo

      - name: Set up Android NDK (r28c)
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c

      - name: Give execute permissions
        run: chmod +x buildscripts/*.sh buildscripts/include/*.sh buildscripts/scripts/*.sh

      - name: Download SDK & dependencies
        run: |
          cd buildscripts
          ./download.sh
          cd ..

      - name: Build native libraries (default official .so)
        run: |
          cd buildscripts
          ./buildall.sh --arch arm64
          cd ..

      - name: Copy .so files into jniLibs
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          cp -v buildscripts/prefix/arm64/usr/local/lib/*.so app/src/main/jniLibs/arm64-v8a/ || true

      - name: Build unsigned release APK
        run: |
          set -x
          ./gradlew assembleRelease | tee build_error_log.txt

      - name: Locate unsigned APK
        id: locate_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/ -name "*arm64-v8a-release-unsigned.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Found APK: $APK_PATH"

      - name: Create test keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore test-release-key.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias mpvkey \
            -storepass android \
            -keypass android \
            -dname "CN=mpv, OU=Dev, O=mpv, L=Internet, ST=World, C=US"

      - name: Find apksigner path
        id: apksigner
        run: |
          APK_SIGNER_PATH=$(find $ANDROID_HOME/build-tools -name apksigner | sort | tail -n 1)
          echo "apksigner_path=$APK_SIGNER_PATH" >> $GITHUB_OUTPUT
          echo "Found apksigner at: $APK_SIGNER_PATH"

      - name: Sign APK
        run: |
          "${{ steps.apksigner.outputs.apksigner_path }}" sign \
            --ks test-release-key.jks \
            --ks-pass pass:android \
            --key-pass pass:android \
            --ks-key-alias mpvkey \
            --out signed-release.apk \
            "${{ steps.locate_apk.outputs.apk_path }}"

      - name: Verify signed APK
        run: |
          "${{ steps.apksigner.outputs.apksigner_path }}" verify --verbose --print-certs signed-release.apk

      - name: Upload signed release APK
        uses: actions/upload-artifact@v4
        with:
          name: mpv-android-arm64-release-signed-${{ github.run_number }}
          path: signed-release.apk

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build_error_log
          path: build_error_log.txt
